version: '3.1'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - DB_URI=mongodb://root:example@mongo:27017/boplats?authSource=admin
    ports:
      - 3000:3000
    depends_on:
      - mongo
  scraper:
    container_name: scraper
    build:
      context: .
      dockerfile: apps/scraper/Dockerfile
    environment:
      - DB_URI=mongodb://root:example@mongo:27017/boplats?authSource=admin
    depends_on:
      - mongo
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    environment:
      - API_URL=http://localhost:3000
    ports:
      - 8082:80

  mongo:
    container_name: mongo
    image: artifactory.local.hejsan.xyz/docker/library/mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: boplats
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://unifi:pass@media.local.hejsan.xyz:27017/unifi-db
    #depends_on:
    # - mongo
