name: Pull Request Validation

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"

jobs:
  validate:
    strategy:
      matrix:
        project:
          [
            { service: new-new-boplats-web, dockerfile: ./apps/web/Dockerfile },
            {
              service: new-new-boplats-scraper,
              dockerfile: ./apps/scraper/Dockerfile,
            },
            { service: new-new-boplats-api, dockerfile: ./apps/api/Dockerfile },
          ]

    uses: josmase/workflows/.github/workflows/docker-build.yaml@main
    name: pull-request-validation
    with:
      registry_url: ${{ vars.REGISTRY_URL }}
      registry_cache_url: ${{ vars.REGISTRY_CACHE_URL }}
      name: josmase/${{ matrix.project.service }}
      dockerfile: ${{ matrix.project.dockerfile }}
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    permissions:
      contents: read
