name: Release Docker image

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    strategy:
      matrix:
        project:
          [
            { service: new-new-boplats-web, dockerfile: ./apps/web/Dockerfile },
            {
              service: new-new-boplats-scraper,
              dockerfile: ./apps/scraper/Dockerfile,
            },
            { service: new-new-boplats-api, dockerfile: ./apps/api/Dockerfile },
          ]

    uses: josmase/workflows/.github/workflows/docker-build.yaml@main
    with:
      registry_url: ${{ vars.REGISTRY_URL }}
      registry_cache_url: ${{ vars.REGISTRY_CACHE_URL }}
      name: josmase/${{ matrix.project.service }}
      dockerfile: ${{ matrix.project.dockerfile }}
      tag: ${{ github.ref_name }}
      push: true
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    permissions:
      contents: read
      attestations: write

  deploy:
    strategy:
      matrix:
        project:
          [
            {
              name: new-new-boplats-web,
              image: new-new-boplats-web,
              file-path: apps/production/new-new-boplats/frontend/deployment.yaml,
              kind: deployment,
            },
            {
              name: new-new-boplats-scraper,
              image: new-new-boplats-scraper,
              file-path: apps/production/new-new-boplats/scraper/deployment.yaml,
              kind: cronjob,
            },
            {
              name: new-new-boplats-api,
              image: new-new-boplats-api,
              file-path: apps/production/new-new-boplats/api/deployment.yaml,
              kind: deployment,
            },
          ]
    needs: publish
    uses: josmase/workflows/.github/workflows/deploy.yaml@main
    with:
      image-version: ${{ github.ref_name }}
      image-name: josmase/${{ matrix.project.image }}
      file-path: ${{ matrix.project.file-path }}
      repository: josmase/flux
      namespace: default
      kind: ${{ matrix.project.kind }}
      name: ${{ matrix.project.name }}
    secrets:
      github-token: ${{ secrets.AUTO_DEPLOY_PAT }}
      kubeconfig: ${{ secrets.KUBECONFIG }}
    permissions:
      contents: read
      deployments: write
