name: Release Docker image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-docker-image:
    strategy:
      matrix:
        project:
          [
            {
              service: new-new-boplats-frontend,
              dockerfile: ./apps/frontend/Dockerfile,
            },
            {
              service: new-new-boplats-scraper,
              dockerfile: ./apps/scraper/Dockerfile,
            },
            { service: new-new-boplats-api, dockerfile: ./apps/api/Dockerfile },
          ]

    uses: josmase/workflows/.github/workflows/docker-build.yaml@main
    with:
      runner: ${{ vars.RUNNER_NAME }}
      registry_url: ${{ vars.REGISTRY_URL }}
      name: josmase/${{ matrix.project.service }}
      dockerfile: ${{ matrix.project.dockerfile }}
      tag: ${{ github.ref_name }}
      push: true
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    permissions:
      contents: read
      attestations: write
